name = "hono-ssr-react-miniflare"
compatibility_date = "2024-09-25"
main = "./src/server.tsx"
assets = { directory = "./dist"}

services = [
  { binding = "self", service = "hono-ssr-react-miniflare" }
]

[observability]
enabled = true
